# Generated by Django 5.2.7 on 2025-10-13 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('lugar', models.TextField()),
                ('fecha', models.DateTimeField(help_text='Fecha y Hora')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/')),
            ],
        ),
    ]
